name: ptvis
channels:
    - conda-forge
    - defaults
    - pytorch
dependencies:
    - python>=3.10
    #
    - pytorch
    - torchvision>=0.10
    # - cudatoolkit=11.6
    - pytorch-lightning
    - onnx
    - thop
    #
    - scipy
    - numpy
    - matplotlib
    - seaborn
    - Pillow
    - opencv
    - ipython
    - scikit-learn
    - rich
    - loguru
    # dev
    - yapf
    - toml
    - isort
    - pylint
    - mypy